### ISSUE TITLE
Gradle not loading

### ISSUE THREAD

**Issue by Auxnos** [RusherDevelopment/example-plugin#4]
I can't open up the example plugin in Intellij.

The error that I get: "Cannot mutate content repository descriptor 'LoomLocalRemappedMods(file:/D://rusherplugin/.gradle/loom-cache/remapped_mods/)' after repository has been used"

**Comment by Auxnos** [comment]
Fixed via changing Fabric Loom version.

**Comment by John200410** [comment]
Which version did you change it to?

**Comment by Auxnos** [comment]
> Which version did you change it to?

I changed it from 1.2 to 1.1

**Comment by John200410** [comment]
Does the issue happen with the latest version 1.4?

**Comment by Auxnos** [comment]
No clue. Haven't tried yet.

**Comment by Auxnos** [comment]
I'm at school right now so I can't check either.

**Comment by Auxnos** [comment]
> Does the issue happen with the latest version 1.4?

I think this would work, but I'm not 100% sure.
